name: CI

on:
  schedule:
    - cron:  '56 3 * * 1'
  push:
env:
  IMAGE_NAME: vondruska/borgmatic

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm32v7, arm64v8]

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    
    - name: Docker login
      env:
        REGISTRY_USER: ${{secrets.REGISTRY_USER}}
        REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
      run: docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" 
    
    - name: Register QEMU
      run: docker run --rm --privileged hypriot/qemu-register
      
    - uses: satackey/action-docker-layer-caching@v0.0.8
      
    - name: Build docker image
      env:
        ARCH: ${{ matrix.arch }}
      run: docker build --pull -f Dockerfile --build-arg ARCH -t "$IMAGE_NAME:$ARCH-$GITHUB_RUN_ID" .

    - name: Push images
      run: docker push $IMAGE_NAME
    
  manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Docker login
      env:
        REGISTRY_USER: ${{secrets.REGISTRY_USER}}
        REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
      run: docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" 
    - name: Manifest
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      if: github.ref == 'refs/heads/master'
      run: |
        docker manifest create "$IMAGE_NAME:latest" "$IMAGE_NAME:amd64-$GITHUB_RUN_ID" "$IMAGE_NAME:arm64v8-$GITHUB_RUN_ID" "$IMAGE_NAME:arm32v7-$GITHUB_RUN_ID"
        docker manifest push "$IMAGE_NAME:latest"
